# Generated by Django 4.0.5 on 2022-07-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_author_book_bookinstance_genre_delete_directores_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Pelis',
        ),
    ]
