# Generated by Django 4.0.5 on 2022-07-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_book_pelis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pelis',
            new_name='Peliculas',
        ),
    ]
